version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty
    ports:
      - 5432:5432
  api:
    build: .
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - DATABASE_URL=db
    depends_on:
      - db